[workspace]

members = [
    "yk_intervals",
    "yk_regex_parse",
    "yk_dense_fsa",
    "yk_lexer_derive",
    "yk_lexer",
    "yk_lexer_fuzzer",
    "yk_parser_internal",
    "yk_parser",
    "yk_parser_derive",
    "yk_examples",
    "yk_incremental_test",
]
